---
title: "In class Exercise 2 - Beyond Plotting Fundamentals"
---

```{r, include=FALSE}
library(pacman)
pacman::p_load(tidyverse,patchwork,ggthemes,hrbrthemes,ggrepel)
exam_data <- read_csv("data/2/exam_data.csv")
```

Plotting of exam_data dataset, below:

```{r, echo=FALSE}
head(exam_data)
```

1.  Histogram plot for Maths scores

```{r,message=FALSE}
p1 <- ggplot(data=exam_data, 
             aes(x = MATHS)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") + 
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")
```

2.  Histogram plot for English scores

```{r,message=FALSE}
p2 <- ggplot(data=exam_data, 
             aes(x = ENGLISH)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") +
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")
  
```

3.  Scatter plot of English vs Maths scores

```{r, message=FALSE}
p3 <- ggplot(data=exam_data, 
             aes(x= MATHS, 
                 y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English scores versus Maths scores for Primary 3")

```

4.  Bringing it all together - with an economist theme!

```{r,message=FALSE}
patchwork <- (p1 / p2) | p3
patchwork & theme_economist()
```
